# Generated by Django 4.1.7 on 2024-05-24 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_img',
            field=models.ImageField(default='defaultPP.jpg', upload_to='profile_images'),
        ),
    ]
